# Generated by Django 3.0.2 on 2020-11-22 04:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201118_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='post_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog_post',
            name='title_tag',
            field=models.CharField(max_length=255),
        ),
    ]
