# Generated by Django 3.0.2 on 2020-11-23 23:38

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_post_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_post',
            name='body',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
