# Generated by Django 3.0.2 on 2020-11-24 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201124_0238'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_post',
            name='snippet',
            field=models.CharField(default='Read More...', max_length=255),
        ),
    ]
